"""initial_schema

Revision ID: 77305fd9325e
Revises: 
Create Date: 2026-09-29 17:07:37.630980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77305fd9325e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_generation_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('pattern', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('priority')
    )
    with op.batch_alter_table('id_generation_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_id_generation_patterns_id'), ['id'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('attempt_type', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_identifier'), ['identifier'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('father_name', sa.String(length=128), nullable=False),
    sa.Column('mother_name', sa.String(length=128), nullable=False),
    sa.Column('cnic_or_id_card', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('edit_id_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('account_status', sa.String(length=32), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_edit_id_hash'), ['edit_id_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=6), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=32), nullable=False),
    sa.Column('location_scope', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('recipient_name', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('province_state', sa.String(length=128), nullable=True),
    sa.Column('region_division', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('tehsil', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('town', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('locality', sa.String(length=128), nullable=True),
    sa.Column('street', sa.String(length=128), nullable=True),
    sa.Column('road', sa.String(length=128), nullable=True),
    sa.Column('house_number', sa.String(length=64), nullable=True),
    sa.Column('building', sa.String(length=128), nullable=True),
    sa.Column('floor', sa.String(length=32), nullable=True),
    sa.Column('flat', sa.String(length=32), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=False),
    sa.Column('destination_url', sa.String(length=1024), nullable=True),
    sa.Column('redirect_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_address_type'), ['address_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_country'), ['country'], unique=False)
        batch_op.create_index('ix_addresses_country_city', ['country', 'city'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_location_scope'), ['location_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_public_id'), ['public_id'], unique=True)
        batch_op.create_index('ix_addresses_type_scope', ['address_type', 'location_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_visibility'), ['visibility'], unique=False)

    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_id'), ['id'], unique=False)

    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=6), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_logs_accessed_at'), ['accessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_address_id'), ['address_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_public_id'), ['public_id'], unique=False)
        batch_op.create_index('ix_access_logs_time_success', ['accessed_at', 'success'], unique=False)

    op.create_table('address_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('address_snapshot', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_versions_address_id'), ['address_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_versions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_versions_id'))
        batch_op.drop_index(batch_op.f('ix_address_versions_address_id'))

    op.drop_table('address_versions')
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_access_logs_time_success')
        batch_op.drop_index(batch_op.f('ix_access_logs_public_id'))
        batch_op.drop_index(batch_op.f('ix_access_logs_id'))
        batch_op.drop_index(batch_op.f('ix_access_logs_address_id'))
        batch_op.drop_index(batch_op.f('ix_access_logs_accessed_at'))

    op.drop_table('access_logs')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_user_id'))

    op.drop_table('admin_actions')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_visibility'))
        batch_op.drop_index(batch_op.f('ix_addresses_user_id'))
        batch_op.drop_index('ix_addresses_type_scope')
        batch_op.drop_index(batch_op.f('ix_addresses_public_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_location_scope'))
        batch_op.drop_index(batch_op.f('ix_addresses_is_active'))
        batch_op.drop_index(batch_op.f('ix_addresses_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_created_at'))
        batch_op.drop_index('ix_addresses_country_city')
        batch_op.drop_index(batch_op.f('ix_addresses_country'))
        batch_op.drop_index(batch_op.f('ix_addresses_city'))
        batch_op.drop_index(batch_op.f('ix_addresses_address_type'))

    op.drop_table('addresses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_edit_id_hash'))

    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_identifier'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_id'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_attempted_at'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('id_generation_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_id_generation_patterns_id'))

    op.drop_table('id_generation_patterns')
    # ### end Alembic commands ###
